"""검사 항목 참고 정보(lab_references) 시드 데이터.

검사 코드·명칭·일반 참고범위(출처 인용 예시)를 적재한다.
참고범위·상태는 사용자가 검사지를 보고 직접 입력·선택하는 값이며,
본 데이터는 출처를 명시한 일반 참고 예시로만 제공된다
(앱 자동 정상/비정상 판정 없음, REQ-LAB-001).

실행:
    DB_HOST=localhost uv run python -m app.core.db.seeds.lab_reference_seed
"""

import asyncio
import sys

sys.path.insert(0, ".")

SEED_DATA = [
    {
        "code": "CRP",
        "name_ko": "C-반응성 단백",
        "abbr": "CRP",
        "category": "염증지표",
        "description": "급성 염증 지표 · 치료 반응 추적",
        "unit": "mg/L",
        "reference_range_general": "<5 mg/L (또는 <0.5 mg/dL)",
        "reference_note": "단위(mg/L vs mg/dL) 스케일 10배 차이, 검사실별 상이",
        "source": "MedlinePlus 등 일반 임상 참고치",
    },
    {
        "code": "ESR",
        "name_ko": "적혈구 침강 속도",
        "abbr": "ESR",
        "category": "염증지표",
        "description": "전신 염증 정도 · 만성 염증 흐름",
        "unit": "mm/hr",
        "reference_range_general": "남 0–15, 여 0–20 mm/hr",
        "reference_note": "성별·연령 따라 상이",
        "source": "일반 임상 참고치",
    },
    {
        "code": "RF",
        "name_ko": "류마티스 인자",
        "abbr": "RF (RA Factor)",
        "category": "자가항체",
        "description": "RA 가능성 보조 지표 (단독 확진 아님)",
        "unit": "IU/mL",
        "reference_range_general": "<20 IU/mL (음성)",
        "reference_note": "U/mL 로도 보고",
        "source": "Cleveland Clinic",
    },
    {
        "code": "ANTI_CCP",
        "name_ko": "항CCP 항체",
        "abbr": "Anti-CCP / ACPA",
        "category": "자가항체",
        "description": "RA 특이적 자가항체 · 미란성 진행 위험 참고",
        "unit": "U/mL",
        "reference_range_general": "<20 U/mL (음성)",
        "reference_note": "측정 키트별 컷오프 상이",
        "source": "HSS",
    },
    {
        "code": "ANA",
        "name_ko": "항핵항체",
        "abbr": "ANA",
        "category": "자가항체",
        "description": "루푸스·쇼그렌 등 자가면역질환 감별",
        "unit": "역가(titer)",
        "reference_range_general": "음성 (예: <1:40)",
        "reference_note": "역가·패턴으로 보고, 고정 단위 없음",
        "source": "일반 임상 참고치",
    },
    {
        "code": "ANTI_DSDNA",
        "name_ko": "항이중나선DNA 항체",
        "abbr": "Anti-dsDNA",
        "category": "자가항체",
        "description": "루푸스 특이 자가항체 · 수치 상승 시 루푸스 활성도·루푸스 신장염 가능성 참고",
        "unit": "IU/mL",
        "reference_range_general": "음성이 정상 (일부 ELISA 기준: <10 IU/mL 음성, 10–25 경계/약양성, >25 양성)",
        "reference_note": "검사법(ELISA/Farr 등)마다 기준 차이 큼 — 검사지 기준 우선",
        "source": "일반 임상 참고치 (검사법별 상이)",
    },
    {
        "code": "C3",
        "name_ko": "보체 C3",
        "abbr": "C3",
        "category": "자가항체/보체",
        "description": "보체 단백 · 루푸스 활성 시 소모되어 낮아질 수 있음",
        "unit": "mg/dL",
        "reference_range_general": "약 90–180 mg/dL (검사실별 상이)",
        "reference_note": "검사실 기준 우선",
        "source": "일반 임상 참고치",
    },
    {
        "code": "C4",
        "name_ko": "보체 C4",
        "abbr": "C4",
        "category": "자가항체/보체",
        "description": "보체 단백 · C3와 함께 감소 시 루푸스 활성·면역복합체 질환 참고",
        "unit": "mg/dL",
        "reference_range_general": "약 10–40 mg/dL (검사실별 상이)",
        "reference_note": "검사실 기준 우선",
        "source": "일반 임상 참고치",
    },
    {
        "code": "WBC",
        "name_ko": "백혈구 수",
        "abbr": "WBC (CBC)",
        "category": "혈액(CBC)",
        "description": "감염·염증·약물 부작용(감소/증가) 확인",
        "unit": "/µL",
        "reference_range_general": "4,500–11,000 /µL",
        "reference_note": "",
        "source": "MedlinePlus",
    },
    {
        "code": "HB",
        "name_ko": "혈색소",
        "abbr": "Hb (CBC)",
        "category": "혈액(CBC)",
        "description": "빈혈 확인",
        "unit": "g/dL",
        "reference_range_general": "남 13–18, 여 12–16 g/dL",
        "reference_note": "성별 따라 상이",
        "source": "MedlinePlus",
    },
    {
        "code": "PLT",
        "name_ko": "혈소판 수",
        "abbr": "Platelet (CBC)",
        "category": "혈액(CBC)",
        "description": "혈소판 증가/감소 확인",
        "unit": "/µL",
        "reference_range_general": "150,000–400,000 /µL",
        "reference_note": "",
        "source": "MedlinePlus",
    },
    {
        "code": "AST",
        "name_ko": "AST (간효소)",
        "abbr": "AST",
        "category": "간기능",
        "description": "간 기능 · 메토트렉세이트 등 약물 모니터링",
        "unit": "U/L",
        "reference_range_general": "약 10–40 U/L",
        "reference_note": "검사실별 상이",
        "source": "일반 임상 참고치",
    },
    {
        "code": "ALT",
        "name_ko": "ALT (간효소)",
        "abbr": "ALT",
        "category": "간기능",
        "description": "간 기능 · 약물 모니터링",
        "unit": "U/L",
        "reference_range_general": "약 7–56 U/L",
        "reference_note": "검사실별 상이",
        "source": "일반 임상 참고치",
    },
    {
        "code": "ALBUMIN",
        "name_ko": "알부민",
        "abbr": "Albumin",
        "category": "간기능/영양",
        "description": "만성 염증·영양상태·간/신장 참고",
        "unit": "g/dL",
        "reference_range_general": "3.5–5.0 g/dL",
        "reference_note": "",
        "source": "일반 임상 참고치",
    },
    {
        "code": "CREATININE",
        "name_ko": "크레아티닌",
        "abbr": "Creatinine",
        "category": "신장기능",
        "description": "신장 기능 · NSAIDs/메토트렉세이트 안전성",
        "unit": "mg/dL",
        "reference_range_general": "약 0.6–1.3 mg/dL",
        "reference_note": "성별·근육량 따라 상이",
        "source": "일반 임상 참고치",
    },
    {
        "code": "EGFR",
        "name_ko": "사구체여과율(추정)",
        "abbr": "eGFR",
        "category": "신장기능",
        "description": "신장 기능 추정치 · 약물 안전성",
        "unit": "mL/min/1.73m²",
        "reference_range_general": "≥60 mL/min/1.73m²",
        "reference_note": "",
        "source": "일반 임상 참고치",
    },
    {
        "code": "URIC_ACID",
        "name_ko": "요산",
        "abbr": "Uric acid",
        "category": "기타",
        "description": "통풍 감별",
        "unit": "mg/dL",
        "reference_range_general": "남 3.4–7.0, 여 2.4–6.0 mg/dL",
        "reference_note": "성별 따라 상이",
        "source": "일반 임상 참고치",
    },
    {
        "code": "URINALYSIS",
        "name_ko": "소변검사",
        "abbr": "UA",
        "category": "소변",
        "description": "루푸스·신장질환 감별 (단백뇨·혈뇨)",
        "unit": None,
        "reference_range_general": "단백뇨 음성, 혈뇨 음성",
        "reference_note": "정성/반정량 보고",
        "source": "일반 임상 참고치",
    },
    {
        "code": "HBSAG",
        "name_ko": "B형 간염 표면항원",
        "abbr": "HBsAg",
        "category": "감염선별",
        "description": "면역억제 치료 전 재활성화 위험 선별",
        "unit": None,
        "reference_range_general": "음성",
        "reference_note": "",
        "source": "일반 임상 참고치",
    },
    {
        "code": "ANTI_HCV",
        "name_ko": "C형 간염 항체",
        "abbr": "anti-HCV",
        "category": "감염선별",
        "description": "면역억제 치료 전 선별",
        "unit": None,
        "reference_range_general": "음성",
        "reference_note": "",
        "source": "일반 임상 참고치",
    },
    {
        "code": "TB_IGRA",
        "name_ko": "결핵 검사(IGRA)",
        "abbr": "IGRA / TB test",
        "category": "감염선별",
        "description": "생물학제제/JAK 억제제 전 잠복결핵 확인",
        "unit": None,
        "reference_range_general": "음성",
        "reference_note": "",
        "source": "일반 임상 참고치",
    },
    {
        "code": "XRAY_HANDFOOT",
        "name_ko": "X-ray 손/발",
        "abbr": "X-ray",
        "category": "영상(정성)",
        "description": "골미란·관절 간격 감소·진행 정도 확인",
        "unit": None,
        "reference_range_general": "미란·관절 손상 없음(정상)",
        "reference_note": "수치 없는 정성 판독",
        "source": "일반 임상 참고",
    },
    {
        "code": "JOINT_US",
        "name_ko": "관절 초음파",
        "abbr": "US",
        "category": "영상(정성)",
        "description": "활막염·관절액·파워도플러 염증 확인",
        "unit": None,
        "reference_range_general": "활막염·도플러 신호 없음",
        "reference_note": "수치 없는 정성 판독",
        "source": "일반 임상 참고",
    },
    {
        "code": "MRI",
        "name_ko": "MRI",
        "abbr": "MRI",
        "category": "영상(정성)",
        "description": "초기 골미란·활막염·골수부종 확인",
        "unit": None,
        "reference_range_general": "활막염·골미란·골수부종 없음",
        "reference_note": "수치 없는 정성 판독",
        "source": "일반 임상 참고",
    },
    {
        "code": "LDL_C",
        "name_ko": "LDL 콜레스테롤",
        "abbr": "LDL-C",
        "category": "지질",
        "description": "심혈관 위험 평가 · 스테로이드·면역억제제 부작용 모니터링",
        "unit": "mg/dL",
        "reference_range_general": "<100 mg/dL (최적), <130 mg/dL (정상)",
        "reference_note": "심혈관 위험도·기저 질환에 따라 목표치 상이",
        "source": "일반 임상 참고치 (ACC/AHA 기준)",
    },
    {
        "code": "HDL_C",
        "name_ko": "HDL 콜레스테롤",
        "abbr": "HDL-C",
        "category": "지질",
        "description": "심혈관 보호 인자 · 낮을수록 위험",
        "unit": "mg/dL",
        "reference_range_general": "남 ≥40, 여 ≥50 mg/dL",
        "reference_note": "성별 따라 기준 상이",
        "source": "일반 임상 참고치 (ACC/AHA 기준)",
    },
    {
        "code": "TOTAL_CHOL",
        "name_ko": "총콜레스테롤",
        "abbr": "TC",
        "category": "지질",
        "description": "심혈관 위험 종합 평가",
        "unit": "mg/dL",
        "reference_range_general": "<200 mg/dL (정상)",
        "reference_note": "200–239 경계, ≥240 높음",
        "source": "일반 임상 참고치 (NCEP 기준)",
    },
    {
        "code": "TG",
        "name_ko": "중성지방",
        "abbr": "TG (Triglycerides)",
        "category": "지질",
        "description": "지질 대사 · 스테로이드 장기 복용 시 상승 가능",
        "unit": "mg/dL",
        "reference_range_general": "<150 mg/dL (정상)",
        "reference_note": "150–199 경계, 200–499 높음, ≥500 매우 높음",
        "source": "일반 임상 참고치 (NCEP 기준)",
    },
]


async def run() -> None:
    from tortoise import Tortoise

    from app.core.db.databases import TORTOISE_ORM
    from app.models.lab_reference import LabReference

    await Tortoise.init(config=TORTOISE_ORM)
    inserted = 0
    for item in SEED_DATA:
        _, created = await LabReference.get_or_create(
            code=item["code"],
            defaults={k: v for k, v in item.items() if k != "code"},
        )
        if created:
            inserted += 1
    print(f"시드 완료: {inserted}건 삽입 (전체 {len(SEED_DATA)}건)")
    await Tortoise.close_connections()


if __name__ == "__main__":
    asyncio.run(run())
